### ISSUE TITLE
Add Node.js example to meowform in docs

### ISSUE THREAD

**Issue by tewarig** [tewarig/meowForm-docs#4]
what you need to ?
well, meowform allows you to create backend-less forms easily, you just need to make a post request with data to the API endpoint 'https://server.meowform.xyz/form/[yourEmail]&[formName] '
In the code example, you can make a form get input from the user and then send that data to the user by sending a post request to the API endpoint if you get stuck feel free to ping me

what do I need to do?

 make a folder inside 'docs' name it 'Node js  code example'
 write a code example in it and explain how you did it? you can also add a code repo link :)
 make a pr after that :)
resources: -
docs
blog

**Comment by jatnnik** [comment]
Hi, can I work on that?

**Comment by jatnnik** [comment]
Hey, I opened a PR (#7) with the Node.js example code. Could you please add the 'hacktoberfest' topic to the repo, so my PR counts?

**Comment by tewarig** [comment]
done  :)

**Comment by tewarig** [comment]
thanks for your pr
